### ISSUE TITLE
Error in pathway part

### ISSUE THREAD

**Issue by hust-yyan** [Xinglab/PEGASAS#1]
Hello, I was going to use Pegasas to annotate the rmats output functionally, and then I ran the following command:
outdir=/home/PROJECTS/LungCancer/RNAseq/AS/rmats_secondrun/PEGASAS_output
geneExpbySample=/data1/yyan_tmp/LUNG_CANCER/analysis/deseq2_output/all_genes_FPKM_symbol.txt
geneSignatureList=/home/yyan/database/MSigDB/h.all.v7.2.symbols.gmt
groupInfo=/data1/yyan_tmp/LUNG_CANCER/analysis/deseq2_output/grouping_info.txt
PEGASAS pathway \
-o $outdir  -n 2  --plotting  \
$geneExpbySample $geneSignatureList $groupInfo 
I got the following error message:
![image](https://user-images.githubusercontent.com/54279739/109514997-8efb5b80-7ae1-11eb-935e-fa68916df215.png)
this is the geneExpbySample file that I used:
![image](https://user-images.githubusercontent.com/54279739/109515163-beaa6380-7ae1-11eb-97e4-c80f508edb9b.png)
Could you please help me to see what the problem is?

**Comment by ypnngaa-py** [comment]
Hello,
The expression format looks ok(but you may have to remove '"' otherwise it will report another error).
The error in the screenshot is about the format of geneSignatureList input. Can you double check the format of that file? And please check this  https://github.com/Xinglab/PEGASAS#example-pegasas-run from the README, where we provided an example format of the signature input (can be found here: PEGASAS/data/hallmarks50-2.gmt.txt).  It is slightly different than the ones directly downloaded MSigDB, for the purpose of analyzing multiple signatures. 

Let me know.
Yang

**Comment by hust-yyan** [comment]
Thank you very much, this problem is solved now.
